# Generated by Django 3.1.1 on 2021-03-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
